version: '3'
services:
  redis:
    image: "redis:latest"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3001:80"
  api:
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "3000:3000"
